language: c
before_install:
  - sudo apt-get update
  - wget vianneytran.com/code/static/Keil_microC.7z
install:
  - sudo apt-get -y install p7zip
  - sudo apt-get -y install wine
  - sudo 7zr x Keil_microC.7z -o/opt/
  - sudo chmod -R 755 /opt/Keil
  - wine --version
  - wine netsh # Create Wine config files
script:
  - ./build.sh
